/**
 *
 * $Id$
 */
package gfc.validation;

import gfc.Node;

/**
 * A sample validator interface for {@link gfc.Edge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EdgeValidator {
	boolean validate();

	boolean validateSource(Node value);
	boolean validateTarget(Node value);
	boolean validateLabel(String value);
}
