source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               icons/,\
               plugin.xml,\
               plugin.properties,\
               messages.properties
src.includes = src/
jars.compile.order = .
