pluginName=Gfc Plugin
providerName=Sample Plugin Provider, Inc

editorName=Gfc Diagram Editing
context.description=Gfc Diagram Editing
context.name=In Gfc Diagram Editor
newWizardName=Gfc Diagram
newWizardDesc=Creates Gfc diagram.

initDiagramActionLabel=Initialize gfc_diagram diagram file


navigatorContentName=*.gfc_diagram diagram contents
domainNavigatorContentName=*.gfc model contents
update.diagram.name=Update Gfc diagram
update.diagram.description=Perform Gfc diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.br.ufjf.capivara.diagram.general=Gfc Diagram
prefpage.br.ufjf.capivara.diagram.appearance=Appearance
prefpage.br.ufjf.capivara.diagram.connections=Connections
prefpage.br.ufjf.capivara.diagram.printing=Printing
prefpage.br.ufjf.capivara.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.Flowchart_1000=Undefined
metatype.name.EntryNode_2001=EntryNode
metatype.name.ProcessingNode_2002=ProcessingNode
metatype.name.DecisionNode_2003=DecisionNode
metatype.name.LoopDecisionNode_2004=LoopDecisionNode
metatype.name.ExitNode_2005=ExitNode
metatype.name.Edge_4001=Edge

# Commands and menu actions
cmdcategory.name=Gfc Editor Commands
cmdcategory.desc=Gfc Editor Commands

metatype.name.EntryNode_2006=EntryNode
metatype.name.SwitchNode_2006=SwitchNode
metatype.name.CaseNode_2007=CaseNode
metatype.name.ExitNode_2007=ExitNode
metatype.name.SwitchNode_2005=SwitchNode
metatype.name.CaseNode_2006=CaseNode
